### ISSUE TITLE
Някой доуточнения

### ISSUE THREAD

**Issue by mirolm** [misho-knowledge-base/stampit#1]
Най-новия драйвер може да се вземе от:

https://abcircle.com/en/product/2/CIR115B/sim-sized-contact-smart-card-reader/ --> USB Linux Installer

Не е нужно да се използва libcmP11.so - аз го подкарах само с инсталиране на следното:

apt install opensc

Този пакет добавя security device за Firefox и Chrome.

**Comment by micobg** [comment]
Благодаря за уточнението! 
Добавих го. :wink:

**Comment by mirolm** [comment]
:)
